model:
  # model_name: "simsiam"
  model_name: "FDGC"

data_input: 
  dataset_name: IndianPines
  # dataset_name = 'Loukia'
  # dataset_name = 'Dioni'
  # dataset_name = 'hanchuan'
  # dataset_name = "pavia"
  # dataset_name = "Salinas"
  classes: 16
  patch_size: 19
  path_data: E:\HSI_Classification\datasets\

data_split:
  split_type: number
  # number
  # ratio
  # disjoint
  train_num: 100
  val_num: 0
  train_ratio: 0.1
  val_ratio: 0

data_transforms:
  num_components: 32
  batch_size: 256
  remove_zero_labels: True

network_config:
  max_epoch: 100
  learning_rate: 0.01
  weight_decay: 0.001
  lb_smooth: 0.01
  num_nodes: 1 # 1,2,3  Multiples of classes

result_output:
  data_info_start: 1   # 0, 1
  log_interval: 1
  path_weight: E:\HSI_Classification\ZZ_FDGC\weights\
  path_result: E:\HSI_Classification\ZZ_FDGC\result\




